config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "blogs#index"
  
  resources :blogs do
    resources :posts
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :posts
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@blogs = Blog.all
		@users = User.all
	end

	def show
		@blog = Blog.find params[:id]
		@posts = Post.all
		redirect_to blog_posts_path(@blog.id)
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new blog_params
		@blog.user = current_user
		@blog.save!
		redirect_to blogs_path
	end


	def blog_params
		params.require(:blog).permit(:title, :description)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def index
		@posts = Post.all
		@blog = Blog.find params[:blog_id]
		@blog_posts = Post.where(blog_id: params[:blog_id]).order(created_at: :desc)
		@post_months = @blog_posts.group_by{|t| t.created_at.beginning_of_month}
		render :layout => 'blog_layout'
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find params[:id]
		@blog = Blog.find params[:blog_id]
		@blog_posts = Post.where(blog_id: params[:blog_id]).order(created_at: :desc)
		@post_months = @blog_posts.group_by{|t| t.created_at.beginning_of_month}
		render :layout => 'blog_layout'
	end

	def create
		@post = Post.new post_params
		@post.user = current_user
		@post.blog = Blog.find params[:blog_id]
		@post.save!
		
		redirect_to blog_path(@post.blog.id)
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		@post = Post.find params[:id]
		@post.blog = Blog.find params[:blog_id]
		@post.update post_params
		flash[:notice] = "Post successfully updated"
    redirect_to blog_path(@post.blog.id)
	end

	def destroy
		@post = Post.find params[:id]
		@post.destroy
		redirect_to blog_posts_path
		flash[:notice] = "Post successfully deleted"
	end
	
	def post_params
		params.require(:post).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def owner?
		current_user.id == @blog.user_id if current_user
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/index.html.erb
<div class="center-block">
	<div class="starter-template col-md-12">
	<% if current_user %>

		<h1><%= link_to "Add a new blog", new_blog_path(@blog), class: 'btn btn-primary' %></h1>

	<% else %>
		
	  <p class="alert alert-info alert-dismissible">
	  <button type="button" class="close" data-dismiss="alert"></button>
	  You must be logged in to create new blogs</p>

	<% end %>

		<h1>Browse the blogs</h1>

		<% if @blogs.any? %>
			
		<% @blogs.each do |blog| %>
			<div class="col-md-4">
				<div class="panel panel-purple">
					<div class="panel-heading">
						<div class="panel-title">
							<h4><%= link_to "#{blog.title}", blog_path(blog.id) %> <small>(<%= blog.user.email %>)</small></h4>
						</div>
					</div>
					<div class="panel-body">
						<p><%= blog.description %></p>
					</div>
				</div>
			</div>
			<% end %>

		<% else %>
			<div class="panel panel-purple">
				<div class="panel-body">
					<h2>No blog</h2>
				</div>
			</div>

	<% end %>
	</div>
</div>

app/views/blogs/new.html.erb
<%= form_for @blog do |form| %>

	<%= form.label :title %>
	<%= form.text_field :title %>

	<%= form.label :description %>
	<%= form.text_area :description %>

	<%= form.submit "Submit" %>

<% end %>

app/views/blogs/show.html.erb
<%= render 'posts/index' %>

app/views/layouts/_notice.html.erb
<!-- Alerts -->
<% if notice %>
  <p class="alert alert-success alert-dismissible">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger alert-dismissible">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= alert %>
  </p>
<% end %>
<!-- End of alerts -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Megblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- include libries(jQuery, bootstrap, fontawesome) -->
  <script src="//code.jquery.com/jquery-1.9.1.min.js"></script> 
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"> 
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script> 
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MaggieBlog</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            
            <!-- Sign in or sign up form -->
            <% if user_signed_in? %>
              <p>Welcome <%= current_user.email %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></p>
            <% else %>
              <%= form_for(User.new, as: :user, url: session_path(:user), html: { class: 'navbar-form navbar-right' }) do |f| %>
                <%= f.email_field :email, placeholder: 'Email' %>
                <%= f.password_field :password, placeholder: 'Password' %>
                <%= f.button "Sign in" %>
              <% end %>
            <% end %>
            <!-- End of sign in - sign up form -->

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        <!-- Alerts -->
        <% if notice %>
          <p class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= notice %>
          </p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= alert %>
          </p>
        <% end %>
        <!-- End of alerts -->

        <%= yield %>
      </div>

    </div><!-- /.container -->


</body>
</html>

app/views/layouts/blog_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Megblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- include libries(jQuery, bootstrap, fontawesome) -->
  <script src="//code.jquery.com/jquery-1.9.1.min.js"></script> 
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"> 
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script> 
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MaggieBlog</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            
            <!-- Sign in or sign up form -->
            <% if user_signed_in? %>
              <p>Welcome <%= current_user.email %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></p>
            <% else %>
              <%= form_for(User.new, as: :user, url: session_path(:user), html: { class: 'navbar-form navbar-right' }) do |f| %>
                <%= f.email_field :email, placeholder: 'Email' %>
                <%= f.password_field :password, placeholder: 'Password' %>
                <%= f.button "Sign in" %>
              <% end %>
            <% end %>
            <!-- End of sign in - sign up form -->

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        <!-- Alerts -->
        <% if notice %>
          <p class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= notice %>
          </p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= alert %>
          </p>
        <% end %>
        <!-- End of alerts -->

				<div class='container'>
					<div class="well">
						<h1 class="text-center">
							<%= @blog.title %>
						</h1>
						<p class="text-center"><%= @blog.description %></p>
					</div>
					<div class="starter-template col-xs-12 col-md-8">

						<%= yield %>
					</div>

					<div class="col-xs-6 col-md-4">
						<%= render 'panels' %>
					</div>
				</div>
      </div>

    </div><!-- /.container -->


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, url: { action: action } do |form| %>

	<%= form.label :title %>
	<%= form.text_field :title %>

	<%= form.label :description %>
	<%= form.text_area :description %>

	<%= form.submit "Submit" %>

<% end %>

app/views/posts/_panels.html.erb
 <% if !current_user %>

  <p class="alert alert-warning alert-dismissible">
  You must be logged in to add new posts
  </p>

<% else %>
  <% if owner? %>
    <p>
    <%= link_to "New post", new_blog_post_path, class: 'btn btn-success btn-block' %>
    </p>
  <% end %>

<% end %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="panel-title">Blog archive</div>
  </div>
  <div class="panel-body" id="archive">
  	<% @post_months.sort.reverse.each do |month, posts| %>
      <p><%=h month.strftime("%B %Y") %></p>
      <ul>
        <% for post in posts %>
        <li><%=h link_to post.title, blog_post_path(@blog.id, post.id) %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">Panel info</div>
  </div>
  <div class="panel-body">Panel content</div>
</div>
</div>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  		<h2>
  		<%= post.title %>
			<% if owner? %>
				<p class="navbar-right"><small>
				<%= link_to edit_blog_post_path(post.blog_id, post.id), url: {action: "edit"}, id: 'post-edit' do %>
					<span class="glyphicon glyphicon-edit"></span>
				<% end %>
				<%= link_to blog_post_path(post.blog_id, post.id), method: :delete, 'data-confirm' => "Are you sure you want to delete this post?", id: 'post-delete' do %>
					<i class="glyphicon glyphicon-trash"></i>
				<% end %>
				</small></p>
			<% end %>
			</h2>
  </div>

  <div class="panel-body">
		<p><%= post.description %></p>
  </div>

	<div class="panel-footer">
		<p>Posted by <%= post.user.email %> at <%= post.created_at.strftime("%A %d %B %Y, %H:%M") %></p>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Update your post</h1>

<%= render "form", action: "update" %>

app/views/posts/index.html.erb
<% if @blog_posts.any? %>
	<% @blog_posts.each do |post| %>

 		<%= render 'post', post: post %>

	<% end %>
<% else %>
	<h1>No posts yet :(</h1>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", action: "create" %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>